# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: TRIZ Innovation India Forum

# Short description (goes below the title; it will also be used in the RSS feed)
description: Forum created in Disqus for TRIZ Innovation India - discussing TRIZ methods and best practices

# Your name, as you want it to appear underneath each post and in the footer
author: Bala Ramadurai

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
baseurl: /TRIZ-Innovation-India-Forum

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://trizindia.org/forum

# Exclude system files
exclude: [.gitignore]

# The disqus shortname for your forum
disqus_shortname: trizindia

# The public key for your disqus application
disqus_publickey: opXi9gCMbOfHUWER71ps8sO3cKEiDFyL4jG6lmcM2cNqsy6M8e8PZd5XJbuyjbPK
